version: '3'
services:
  issue_tracker_fe:
    image: issue_tracker_fe:latest
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - issue_tracker_be
  issue_tracker_be:
    image: issue_tracker_be:latest
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=issueadmin
      - DB_PASSWORD=issuepassword
      - DB_DATABASE=issue_tracker
      - DB_DIALECT=mysql
      - PORT=8080
    ports:
      - 8090:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=issue_tracker
      - MYSQL_USER=issueadmin
      - MYSQL_PASSWORD=issuepassword
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3806:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10
