import { FETCH_SUCCESS } from '../../../hooks/useAsync';

export default {
  FETCH_SUCCESS,
  SHOW_EDIT_ISSUE_HEADER: 'SHOW_EDIT_ISSUE_HEADER',
  SHOW_EDIT_ISSUE_DETAIL: 'SHOW_EDIT_ISSUE_DETAIL',
  UPDATE_TITLE: 'UPDATE_TITLE',
  SUCCESS_UPDATE_TITLE: 'SUCCESS_UPDATE_TITLE',
};
