import { FETCH_SUCCESS } from '../../../hooks/useAsync';

export default {
  FETCH_SUCCESS,
  REGISTER_COMMENT: 'REGISTER_COMMENT',
  SUCCESS_UPDATE_TITLE: 'SUCCESS_UPDATE_TITLE',
  SUCCESS_UPDATE_CONTENTS: 'SUCCESS_UPDATE_CONTENTS',
  UPDATE_ONE_STATE: 'UPDATE_ONE_STATE',
};
